language: python
python:
- 2.7
- 3.5
install:
- pip install coveralls
script:
- nosetests -c .noserc
- pip install git+git://github.com/pyblish/pyblish-base.git
after_success:
- coveralls
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist bdist_wheel"
  password:
    secure: fwXIOGKn38gJFNkzlpvholQBhSBzNorOnMvs04JT3+Fdq6ys2TiUV6tlXHDwo6DkMY++USI19oD9NWlvg8gQaRJq4g2V/taazn8XDv1XnyKLzb6DnAT1ALilJtbIgotH/0QNOvkDP40a8UDwbelE0aR4AptNO1Ts7n1eERygENA=
  on:
    tags: true
    all_branches: true
    python: 2.7
sudo: false
